swagger: '2.0'
info:
  title: athena-api
  description: API for Athena GenAI application with Vertex AI, AlloyDB, and Firebase integration
  version: 1.0.0
host: ${API_GATEWAY_HOST}
schemes:
  - https
produces:
  - application/json
consumes:
  - application/json
paths:
  # Cloudstore direct endpoints
  /v1/cloudstore/storage-get:
    get:
      operationId: cloudstoreStorageGet
      summary: List files
      description: List all files in storage
      responses:
        200:
          description: Successful response
      x-google-backend:
        address: ${CLOUDSTORE_SERVICE_URL}/storage-get
        deadline: 60.0
  
  /v1/cloudstore/storage-post:
    post:
      operationId: cloudstoreStoragePost
      summary: Generate signed URL
      description: Generate a signed URL for file upload
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              filename:
                type: string
                description: Name of the file to generate signed URL for
      responses:
        200:
          description: Successful response
      x-google-backend:
        address: ${CLOUDSTORE_SERVICE_URL}/storage-post
        deadline: 60.0
  
  /v1/cloudstore/storage-delete:
    delete:
      operationId: cloudstoreStorageDelete
      summary: Delete file
      description: Delete a file from storage
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              filename:
                type: string
                description: Name of the file to delete
      responses:
        200:
          description: Successful response
        404:
          description: Resource not found
      x-google-backend:
        address: ${CLOUDSTORE_SERVICE_URL}/storage-delete
        deadline: 60.0
  
  # VertexAI direct endpoints
  /v1/vertexai/summarize_video:
    post:
      operationId: vertexaiSummarizeVideo
      summary: Summarize video
      description: Generate a summary of a video
      parameters:
        - name: video_link
          in: query
          required: true
          type: string
          description: Link to video for summarization
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              summary:
                type: string
                description: Generated summary
              error:
                type: string
                description: Error message if processing failed
      x-google-backend:
        address: ${VERTEXAI_SERVICE_URL}/summarize_video
        deadline: 300.0  # 5 minute timeout for video processing
  
  /v1/vertexai/generate_quiz:
    post:
      operationId: vertexaiGenerateQuiz
      summary: Generate quiz
      description: Generate a quiz based on provided text
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              text:
                type: string
                description: Text content for quiz generation
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              quiz:
                type: string
                description: Generated quiz
              error:
                type: string
                description: Error message if processing failed
      x-google-backend:
        address: ${VERTEXAI_SERVICE_URL}/generate_quiz
        deadline: 120.0  # 2 minute timeout
  
  /v1/vertexai/generate_summary:
    post:
      operationId: vertexaiGenerateSummary
      summary: Generate summary
      description: Generate a summary of provided text
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              text:
                type: string
                description: Text content for summarization
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              summary:
                type: string
                description: Generated summary
              error:
                type: string
                description: Error message if processing failed
      x-google-backend:
        address: ${VERTEXAI_SERVICE_URL}/generate_summary
        deadline: 120.0  # 2 minute timeout
  
securityDefinitions:
  api_key:
    type: apiKey
    name: key
    in: query